server:
  #port: 9090
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:springboot_demo}
#    username: ${MYSQL_USERNAME}
#    password: ${MySQL_PASSWORD}
    url: jdbc:mysql://sh-cynosdbmysql-grp-5ljk41ng.sql.tencentcdb.com:28513/springboot_demo?characterEncoding=utf-8&useUnicode=true&serverTimezone=US/Central
    username: root
    password: NST4VU3f

  mvc:
    view:
      suffix: .html
      prefix: /

  mail:
    host: smtp.gmail.com
    port: 587
    username: cssanoreply@gmail.com
    password: yjxgxsbtuppfjxhf
    protocol: smtp
    default-encoding: UTF-8
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com




mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  config-location:  classpath:mapper/mybatis-config.xml

jwt:
  header: Authorization
  secret: cssauwmadisoncssauwmadisoncssauwmadisoncssauwmadisoncssauwmadisoncssauwmadisoncssauwmadisoncssauwmadison
  expiration: 31536000