server:
  port: 80


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/cssa_mini?characterEncoding=utf-8&useUnicode=true&serverTimezone=US/Central
    username: ${MYSQL_USERNAME}
    password: ${MySQL_PASSWORD}
#    url: jdbc:mysql://sh-cynosdbmysql-grp-cmngutoy.sql.tencentcdb.com:23504/cssa_mini?characterEncoding=utf-8&useUnicode=true&serverTimezone=US/Central
#    username: root
#    password: r7btwuTa
  redis:
    port: 6379
    host: 47.97.183.103
    timeout: 10000
    jedis:
      pool:
        max-active: 10
        min-idle: 2
        max-idle: 8

  mvc:
    view:
      suffix: .html
      prefix: /



  mail:
    host: smtp.163.com
    port: 465
    username: cssaatuwmadison@163.com
    password: SGOUOBWZZZTEDIAB
    protocol: smtps
    default-encoding: UTF-8
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.163.com




mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  config-location:  classpath:mapper/mybatis-config.xml

jwt:
  header: Authorization
  secret: cssauwmadisoncssauwmadisoncssauwmadisoncssauwmadisoncssauwmadisoncssauwmadisoncssauwmadisoncssauwmadison
  expiration: 31536000




