server:
  port: 80


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/springboot_demo?characterEncoding=utf-8&useUnicode=true&serverTimezone=US/Central
    username: ${MYSQL_USERNAME}
    password: ${MySQL_PASSWORD}
  redis:
    port: 6379
    host: localhost
    timeout: 10000
    jedis:
      pool:
        max-active: 10
        min-idle: 2
        max-idle: 8

  mvc:
    view:
      suffix: .html
      prefix: /

  mail:
    host: smtp.gmail.com
    port: 587
    username: cssanoreply@gmail.com
    password: yjxgxsbtuppfjxhf
    protocol: smtp
    default-encoding: UTF-8
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com




mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  config-location:  classpath:mapper/mybatis-config.xml

jwt:
  header: Authorization
  secret: cssauwmadisoncssauwmadisoncssauwmadisoncssauwmadisoncssauwmadisoncssauwmadisoncssauwmadisoncssauwmadison
  expiration: 31536000




